[2024-01-29T19:53:42.573+0100] {processor.py:161} INFO - Started process (PID=7790) to work on /home/ubuntu/airflow/dags/FilmDag.py
[2024-01-29T19:53:42.582+0100] {processor.py:830} INFO - Processing file /home/ubuntu/airflow/dags/FilmDag.py for tasks to queue
[2024-01-29T19:53:42.605+0100] {logging_mixin.py:188} INFO - [2024-01-29T19:53:42.589+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/FilmDag.py
[2024-01-29T19:53:42.617+0100] {logging_mixin.py:188} INFO - [2024-01-29T19:53:42.615+0100] {dagbag.py:348} ERROR - Failed to import: /home/ubuntu/airflow/dags/FilmDag.py
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/FilmDag.py", line 1, in <module>
    User
NameError: name 'User' is not defined
[2024-01-29T19:53:42.620+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/FilmDag.py
[2024-01-29T19:53:42.819+0100] {processor.py:183} INFO - Processing /home/ubuntu/airflow/dags/FilmDag.py took 0.287 seconds
[2024-01-29T19:55:10.333+0100] {processor.py:161} INFO - Started process (PID=7914) to work on /home/ubuntu/airflow/dags/FilmDag.py
[2024-01-29T19:55:10.409+0100] {processor.py:830} INFO - Processing file /home/ubuntu/airflow/dags/FilmDag.py for tasks to queue
[2024-01-29T19:55:10.418+0100] {logging_mixin.py:188} INFO - [2024-01-29T19:55:10.410+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/FilmDag.py
[2024-01-29T19:55:10.438+0100] {logging_mixin.py:188} INFO - [2024-01-29T19:55:10.435+0100] {dagbag.py:348} ERROR - Failed to import: /home/ubuntu/airflow/dags/FilmDag.py
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/FilmDag.py", line 1, in <module>
    User
NameError: name 'User' is not defined
[2024-01-29T19:55:10.438+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/FilmDag.py
[2024-01-29T19:55:10.620+0100] {processor.py:183} INFO - Processing /home/ubuntu/airflow/dags/FilmDag.py took 0.305 seconds
[2024-01-29T19:55:47.391+0100] {processor.py:161} INFO - Started process (PID=7955) to work on /home/ubuntu/airflow/dags/FilmDag.py
[2024-01-29T19:55:47.422+0100] {processor.py:830} INFO - Processing file /home/ubuntu/airflow/dags/FilmDag.py for tasks to queue
[2024-01-29T19:55:47.432+0100] {logging_mixin.py:188} INFO - [2024-01-29T19:55:47.423+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/FilmDag.py
[2024-01-29T19:55:47.451+0100] {logging_mixin.py:188} INFO - [2024-01-29T19:55:47.449+0100] {dagbag.py:348} ERROR - Failed to import: /home/ubuntu/airflow/dags/FilmDag.py
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/FilmDag.py", line 6, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-01-29T19:55:47.452+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/FilmDag.py
[2024-01-29T19:55:47.823+0100] {processor.py:183} INFO - Processing /home/ubuntu/airflow/dags/FilmDag.py took 0.453 seconds
[2024-01-29T19:56:34.416+0100] {processor.py:161} INFO - Started process (PID=7991) to work on /home/ubuntu/airflow/dags/FilmDag.py
[2024-01-29T19:56:34.421+0100] {processor.py:830} INFO - Processing file /home/ubuntu/airflow/dags/FilmDag.py for tasks to queue
[2024-01-29T19:56:34.426+0100] {logging_mixin.py:188} INFO - [2024-01-29T19:56:34.425+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/FilmDag.py
[2024-01-29T19:56:34.442+0100] {logging_mixin.py:188} INFO - [2024-01-29T19:56:34.436+0100] {dagbag.py:348} ERROR - Failed to import: /home/ubuntu/airflow/dags/FilmDag.py
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/FilmDag.py", line 6, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-01-29T19:56:34.443+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/FilmDag.py
[2024-01-29T19:56:34.496+0100] {processor.py:183} INFO - Processing /home/ubuntu/airflow/dags/FilmDag.py took 0.085 seconds
[2024-01-29T19:57:16.044+0100] {processor.py:161} INFO - Started process (PID=8035) to work on /home/ubuntu/airflow/dags/FilmDag.py
[2024-01-29T19:57:16.047+0100] {processor.py:830} INFO - Processing file /home/ubuntu/airflow/dags/FilmDag.py for tasks to queue
[2024-01-29T19:57:16.049+0100] {logging_mixin.py:188} INFO - [2024-01-29T19:57:16.049+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/FilmDag.py
[2024-01-29T19:57:16.054+0100] {logging_mixin.py:188} INFO - [2024-01-29T19:57:16.053+0100] {dagbag.py:348} ERROR - Failed to import: /home/ubuntu/airflow/dags/FilmDag.py
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/FilmDag.py", line 6, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-01-29T19:57:16.054+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/FilmDag.py
[2024-01-29T19:57:16.093+0100] {processor.py:183} INFO - Processing /home/ubuntu/airflow/dags/FilmDag.py took 0.054 seconds
[2024-01-29T19:58:09.539+0100] {processor.py:161} INFO - Started process (PID=8095) to work on /home/ubuntu/airflow/dags/FilmDag.py
[2024-01-29T19:58:09.541+0100] {processor.py:830} INFO - Processing file /home/ubuntu/airflow/dags/FilmDag.py for tasks to queue
[2024-01-29T19:58:09.543+0100] {logging_mixin.py:188} INFO - [2024-01-29T19:58:09.543+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/FilmDag.py
[2024-01-29T19:58:09.549+0100] {logging_mixin.py:188} INFO - [2024-01-29T19:58:09.548+0100] {dagbag.py:348} ERROR - Failed to import: /home/ubuntu/airflow/dags/FilmDag.py
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/FilmDag.py", line 6, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-01-29T19:58:09.549+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/FilmDag.py
[2024-01-29T19:58:09.587+0100] {processor.py:183} INFO - Processing /home/ubuntu/airflow/dags/FilmDag.py took 0.054 seconds
[2024-01-29T19:58:55.128+0100] {processor.py:161} INFO - Started process (PID=8148) to work on /home/ubuntu/airflow/dags/FilmDag.py
[2024-01-29T19:58:55.131+0100] {processor.py:830} INFO - Processing file /home/ubuntu/airflow/dags/FilmDag.py for tasks to queue
[2024-01-29T19:58:55.132+0100] {logging_mixin.py:188} INFO - [2024-01-29T19:58:55.131+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/FilmDag.py
[2024-01-29T19:58:55.137+0100] {logging_mixin.py:188} INFO - [2024-01-29T19:58:55.136+0100] {dagbag.py:348} ERROR - Failed to import: /home/ubuntu/airflow/dags/FilmDag.py
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/FilmDag.py", line 6, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-01-29T19:58:55.138+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/FilmDag.py
[2024-01-29T19:58:55.167+0100] {processor.py:183} INFO - Processing /home/ubuntu/airflow/dags/FilmDag.py took 0.042 seconds
[2024-01-29T19:59:38.068+0100] {processor.py:161} INFO - Started process (PID=8203) to work on /home/ubuntu/airflow/dags/FilmDag.py
[2024-01-29T19:59:38.070+0100] {processor.py:830} INFO - Processing file /home/ubuntu/airflow/dags/FilmDag.py for tasks to queue
[2024-01-29T19:59:38.073+0100] {logging_mixin.py:188} INFO - [2024-01-29T19:59:38.072+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/FilmDag.py
[2024-01-29T19:59:38.080+0100] {logging_mixin.py:188} INFO - [2024-01-29T19:59:38.079+0100] {dagbag.py:348} ERROR - Failed to import: /home/ubuntu/airflow/dags/FilmDag.py
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/FilmDag.py", line 6, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-01-29T19:59:38.081+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/FilmDag.py
[2024-01-29T19:59:38.121+0100] {processor.py:183} INFO - Processing /home/ubuntu/airflow/dags/FilmDag.py took 0.059 seconds
[2024-01-29T20:00:18.889+0100] {processor.py:161} INFO - Started process (PID=8237) to work on /home/ubuntu/airflow/dags/FilmDag.py
[2024-01-29T20:00:18.908+0100] {processor.py:830} INFO - Processing file /home/ubuntu/airflow/dags/FilmDag.py for tasks to queue
[2024-01-29T20:00:18.909+0100] {logging_mixin.py:188} INFO - [2024-01-29T20:00:18.909+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/FilmDag.py
[2024-01-29T20:00:18.962+0100] {logging_mixin.py:188} INFO - [2024-01-29T20:00:18.946+0100] {dagbag.py:348} ERROR - Failed to import: /home/ubuntu/airflow/dags/FilmDag.py
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/FilmDag.py", line 6, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-01-29T20:00:18.967+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/FilmDag.py
[2024-01-29T20:00:19.088+0100] {processor.py:183} INFO - Processing /home/ubuntu/airflow/dags/FilmDag.py took 0.223 seconds
[2024-01-29T20:01:02.296+0100] {processor.py:161} INFO - Started process (PID=8280) to work on /home/ubuntu/airflow/dags/FilmDag.py
[2024-01-29T20:01:02.298+0100] {processor.py:830} INFO - Processing file /home/ubuntu/airflow/dags/FilmDag.py for tasks to queue
[2024-01-29T20:01:02.299+0100] {logging_mixin.py:188} INFO - [2024-01-29T20:01:02.299+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/FilmDag.py
[2024-01-29T20:01:02.304+0100] {logging_mixin.py:188} INFO - [2024-01-29T20:01:02.303+0100] {dagbag.py:348} ERROR - Failed to import: /home/ubuntu/airflow/dags/FilmDag.py
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/FilmDag.py", line 6, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-01-29T20:01:02.304+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/FilmDag.py
[2024-01-29T20:01:02.337+0100] {processor.py:183} INFO - Processing /home/ubuntu/airflow/dags/FilmDag.py took 0.046 seconds
[2024-01-29T20:01:50.140+0100] {processor.py:161} INFO - Started process (PID=8335) to work on /home/ubuntu/airflow/dags/FilmDag.py
[2024-01-29T20:01:50.148+0100] {processor.py:830} INFO - Processing file /home/ubuntu/airflow/dags/FilmDag.py for tasks to queue
[2024-01-29T20:01:50.149+0100] {logging_mixin.py:188} INFO - [2024-01-29T20:01:50.149+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/FilmDag.py
[2024-01-29T20:01:50.156+0100] {logging_mixin.py:188} INFO - [2024-01-29T20:01:50.154+0100] {dagbag.py:348} ERROR - Failed to import: /home/ubuntu/airflow/dags/FilmDag.py
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/FilmDag.py", line 6, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-01-29T20:01:50.157+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/FilmDag.py
[2024-01-29T20:01:50.185+0100] {processor.py:183} INFO - Processing /home/ubuntu/airflow/dags/FilmDag.py took 0.051 seconds
[2024-01-29T20:02:41.440+0100] {processor.py:161} INFO - Started process (PID=8423) to work on /home/ubuntu/airflow/dags/FilmDag.py
[2024-01-29T20:02:41.458+0100] {processor.py:830} INFO - Processing file /home/ubuntu/airflow/dags/FilmDag.py for tasks to queue
[2024-01-29T20:02:41.462+0100] {logging_mixin.py:188} INFO - [2024-01-29T20:02:41.459+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/FilmDag.py
[2024-01-29T20:02:41.481+0100] {logging_mixin.py:188} INFO - [2024-01-29T20:02:41.479+0100] {dagbag.py:348} ERROR - Failed to import: /home/ubuntu/airflow/dags/FilmDag.py
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/FilmDag.py", line 6, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-01-29T20:02:41.482+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/FilmDag.py
[2024-01-29T20:02:41.703+0100] {processor.py:183} INFO - Processing /home/ubuntu/airflow/dags/FilmDag.py took 0.273 seconds
[2024-01-29T20:03:15.187+0100] {processor.py:161} INFO - Started process (PID=8459) to work on /home/ubuntu/airflow/dags/FilmDag.py
[2024-01-29T20:03:15.192+0100] {processor.py:830} INFO - Processing file /home/ubuntu/airflow/dags/FilmDag.py for tasks to queue
[2024-01-29T20:03:15.194+0100] {logging_mixin.py:188} INFO - [2024-01-29T20:03:15.193+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/FilmDag.py
[2024-01-29T20:03:15.204+0100] {logging_mixin.py:188} INFO - [2024-01-29T20:03:15.201+0100] {dagbag.py:348} ERROR - Failed to import: /home/ubuntu/airflow/dags/FilmDag.py
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/FilmDag.py", line 6, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-01-29T20:03:15.206+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/FilmDag.py
[2024-01-29T20:03:15.249+0100] {processor.py:183} INFO - Processing /home/ubuntu/airflow/dags/FilmDag.py took 0.069 seconds
[2024-01-29T20:04:01.221+0100] {processor.py:161} INFO - Started process (PID=8516) to work on /home/ubuntu/airflow/dags/FilmDag.py
[2024-01-29T20:04:01.223+0100] {processor.py:830} INFO - Processing file /home/ubuntu/airflow/dags/FilmDag.py for tasks to queue
[2024-01-29T20:04:01.225+0100] {logging_mixin.py:188} INFO - [2024-01-29T20:04:01.224+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/FilmDag.py
[2024-01-29T20:04:01.230+0100] {logging_mixin.py:188} INFO - [2024-01-29T20:04:01.229+0100] {dagbag.py:348} ERROR - Failed to import: /home/ubuntu/airflow/dags/FilmDag.py
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/FilmDag.py", line 6, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-01-29T20:04:01.231+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/FilmDag.py
[2024-01-29T20:04:01.260+0100] {processor.py:183} INFO - Processing /home/ubuntu/airflow/dags/FilmDag.py took 0.044 seconds
[2024-01-29T20:04:52.589+0100] {processor.py:161} INFO - Started process (PID=8577) to work on /home/ubuntu/airflow/dags/FilmDag.py
[2024-01-29T20:04:52.605+0100] {processor.py:830} INFO - Processing file /home/ubuntu/airflow/dags/FilmDag.py for tasks to queue
[2024-01-29T20:04:52.607+0100] {logging_mixin.py:188} INFO - [2024-01-29T20:04:52.606+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/FilmDag.py
[2024-01-29T20:04:52.637+0100] {logging_mixin.py:188} INFO - [2024-01-29T20:04:52.633+0100] {dagbag.py:348} ERROR - Failed to import: /home/ubuntu/airflow/dags/FilmDag.py
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/FilmDag.py", line 6, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-01-29T20:04:52.641+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/FilmDag.py
[2024-01-29T20:04:52.692+0100] {processor.py:183} INFO - Processing /home/ubuntu/airflow/dags/FilmDag.py took 0.135 seconds
[2024-01-29T20:05:31.238+0100] {processor.py:161} INFO - Started process (PID=8612) to work on /home/ubuntu/airflow/dags/FilmDag.py
[2024-01-29T20:05:31.241+0100] {processor.py:830} INFO - Processing file /home/ubuntu/airflow/dags/FilmDag.py for tasks to queue
[2024-01-29T20:05:31.242+0100] {logging_mixin.py:188} INFO - [2024-01-29T20:05:31.242+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/FilmDag.py
[2024-01-29T20:05:31.247+0100] {logging_mixin.py:188} INFO - [2024-01-29T20:05:31.246+0100] {dagbag.py:348} ERROR - Failed to import: /home/ubuntu/airflow/dags/FilmDag.py
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/FilmDag.py", line 6, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-01-29T20:05:31.247+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/FilmDag.py
[2024-01-29T20:05:31.276+0100] {processor.py:183} INFO - Processing /home/ubuntu/airflow/dags/FilmDag.py took 0.041 seconds
[2024-01-29T20:06:04.904+0100] {processor.py:161} INFO - Started process (PID=8653) to work on /home/ubuntu/airflow/dags/FilmDag.py
[2024-01-29T20:06:04.920+0100] {processor.py:830} INFO - Processing file /home/ubuntu/airflow/dags/FilmDag.py for tasks to queue
[2024-01-29T20:06:04.927+0100] {logging_mixin.py:188} INFO - [2024-01-29T20:06:04.924+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/FilmDag.py
[2024-01-29T20:06:04.956+0100] {logging_mixin.py:188} INFO - [2024-01-29T20:06:04.949+0100] {dagbag.py:348} ERROR - Failed to import: /home/ubuntu/airflow/dags/FilmDag.py
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/FilmDag.py", line 6, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-01-29T20:06:04.957+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/FilmDag.py
[2024-01-29T20:06:05.073+0100] {processor.py:183} INFO - Processing /home/ubuntu/airflow/dags/FilmDag.py took 0.211 seconds
[2024-01-29T20:06:50.442+0100] {processor.py:161} INFO - Started process (PID=8689) to work on /home/ubuntu/airflow/dags/FilmDag.py
[2024-01-29T20:06:50.444+0100] {processor.py:830} INFO - Processing file /home/ubuntu/airflow/dags/FilmDag.py for tasks to queue
[2024-01-29T20:06:50.446+0100] {logging_mixin.py:188} INFO - [2024-01-29T20:06:50.445+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/FilmDag.py
[2024-01-29T20:06:50.450+0100] {logging_mixin.py:188} INFO - [2024-01-29T20:06:50.449+0100] {dagbag.py:348} ERROR - Failed to import: /home/ubuntu/airflow/dags/FilmDag.py
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/FilmDag.py", line 6, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-01-29T20:06:50.450+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/FilmDag.py
[2024-01-29T20:06:50.477+0100] {processor.py:183} INFO - Processing /home/ubuntu/airflow/dags/FilmDag.py took 0.038 seconds
[2024-01-29T20:07:27.116+0100] {processor.py:161} INFO - Started process (PID=8735) to work on /home/ubuntu/airflow/dags/FilmDag.py
[2024-01-29T20:07:27.119+0100] {processor.py:830} INFO - Processing file /home/ubuntu/airflow/dags/FilmDag.py for tasks to queue
[2024-01-29T20:07:27.121+0100] {logging_mixin.py:188} INFO - [2024-01-29T20:07:27.120+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/FilmDag.py
[2024-01-29T20:07:27.130+0100] {logging_mixin.py:188} INFO - [2024-01-29T20:07:27.128+0100] {dagbag.py:348} ERROR - Failed to import: /home/ubuntu/airflow/dags/FilmDag.py
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/FilmDag.py", line 6, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-01-29T20:07:27.131+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/FilmDag.py
[2024-01-29T20:07:27.221+0100] {processor.py:183} INFO - Processing /home/ubuntu/airflow/dags/FilmDag.py took 0.111 seconds
[2024-01-29T20:07:57.967+0100] {processor.py:161} INFO - Started process (PID=8766) to work on /home/ubuntu/airflow/dags/FilmDag.py
[2024-01-29T20:07:57.969+0100] {processor.py:830} INFO - Processing file /home/ubuntu/airflow/dags/FilmDag.py for tasks to queue
[2024-01-29T20:07:57.970+0100] {logging_mixin.py:188} INFO - [2024-01-29T20:07:57.970+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/FilmDag.py
[2024-01-29T20:07:57.974+0100] {logging_mixin.py:188} INFO - [2024-01-29T20:07:57.973+0100] {dagbag.py:348} ERROR - Failed to import: /home/ubuntu/airflow/dags/FilmDag.py
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/FilmDag.py", line 6, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-01-29T20:07:57.975+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/FilmDag.py
[2024-01-29T20:07:58.002+0100] {processor.py:183} INFO - Processing /home/ubuntu/airflow/dags/FilmDag.py took 0.040 seconds
[2024-01-29T20:08:48.114+0100] {processor.py:161} INFO - Started process (PID=8824) to work on /home/ubuntu/airflow/dags/FilmDag.py
[2024-01-29T20:08:48.116+0100] {processor.py:830} INFO - Processing file /home/ubuntu/airflow/dags/FilmDag.py for tasks to queue
[2024-01-29T20:08:48.117+0100] {logging_mixin.py:188} INFO - [2024-01-29T20:08:48.117+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/FilmDag.py
[2024-01-29T20:08:48.123+0100] {logging_mixin.py:188} INFO - [2024-01-29T20:08:48.122+0100] {dagbag.py:348} ERROR - Failed to import: /home/ubuntu/airflow/dags/FilmDag.py
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/FilmDag.py", line 6, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-01-29T20:08:48.123+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/FilmDag.py
[2024-01-29T20:08:48.155+0100] {processor.py:183} INFO - Processing /home/ubuntu/airflow/dags/FilmDag.py took 0.045 seconds
[2024-01-29T20:09:31.026+0100] {processor.py:161} INFO - Started process (PID=8873) to work on /home/ubuntu/airflow/dags/FilmDag.py
[2024-01-29T20:09:31.028+0100] {processor.py:830} INFO - Processing file /home/ubuntu/airflow/dags/FilmDag.py for tasks to queue
[2024-01-29T20:09:31.030+0100] {logging_mixin.py:188} INFO - [2024-01-29T20:09:31.030+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/FilmDag.py
[2024-01-29T20:09:31.035+0100] {logging_mixin.py:188} INFO - [2024-01-29T20:09:31.034+0100] {dagbag.py:348} ERROR - Failed to import: /home/ubuntu/airflow/dags/FilmDag.py
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/FilmDag.py", line 6, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-01-29T20:09:31.035+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/FilmDag.py
[2024-01-29T20:09:31.065+0100] {processor.py:183} INFO - Processing /home/ubuntu/airflow/dags/FilmDag.py took 0.043 seconds
[2024-01-29T20:10:20.103+0100] {processor.py:161} INFO - Started process (PID=8938) to work on /home/ubuntu/airflow/dags/FilmDag.py
[2024-01-29T20:10:20.106+0100] {processor.py:830} INFO - Processing file /home/ubuntu/airflow/dags/FilmDag.py for tasks to queue
[2024-01-29T20:10:20.108+0100] {logging_mixin.py:188} INFO - [2024-01-29T20:10:20.108+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/FilmDag.py
[2024-01-29T20:10:20.114+0100] {logging_mixin.py:188} INFO - [2024-01-29T20:10:20.113+0100] {dagbag.py:348} ERROR - Failed to import: /home/ubuntu/airflow/dags/FilmDag.py
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/FilmDag.py", line 6, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-01-29T20:10:20.115+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/FilmDag.py
[2024-01-29T20:10:20.151+0100] {processor.py:183} INFO - Processing /home/ubuntu/airflow/dags/FilmDag.py took 0.053 seconds
[2024-01-29T20:11:09.714+0100] {processor.py:161} INFO - Started process (PID=8994) to work on /home/ubuntu/airflow/dags/FilmDag.py
[2024-01-29T20:11:09.716+0100] {processor.py:830} INFO - Processing file /home/ubuntu/airflow/dags/FilmDag.py for tasks to queue
[2024-01-29T20:11:09.719+0100] {logging_mixin.py:188} INFO - [2024-01-29T20:11:09.718+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/FilmDag.py
[2024-01-29T20:11:09.725+0100] {logging_mixin.py:188} INFO - [2024-01-29T20:11:09.724+0100] {dagbag.py:348} ERROR - Failed to import: /home/ubuntu/airflow/dags/FilmDag.py
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/FilmDag.py", line 6, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-01-29T20:11:09.726+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/FilmDag.py
[2024-01-29T20:11:09.823+0100] {processor.py:183} INFO - Processing /home/ubuntu/airflow/dags/FilmDag.py took 0.114 seconds
[2024-01-29T20:12:03.046+0100] {processor.py:161} INFO - Started process (PID=9069) to work on /home/ubuntu/airflow/dags/FilmDag.py
[2024-01-29T20:12:03.093+0100] {processor.py:830} INFO - Processing file /home/ubuntu/airflow/dags/FilmDag.py for tasks to queue
[2024-01-29T20:12:03.095+0100] {logging_mixin.py:188} INFO - [2024-01-29T20:12:03.094+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/FilmDag.py
[2024-01-29T20:12:03.133+0100] {logging_mixin.py:188} INFO - [2024-01-29T20:12:03.117+0100] {dagbag.py:348} ERROR - Failed to import: /home/ubuntu/airflow/dags/FilmDag.py
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/FilmDag.py", line 6, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-01-29T20:12:03.136+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/FilmDag.py
[2024-01-29T20:12:03.495+0100] {processor.py:183} INFO - Processing /home/ubuntu/airflow/dags/FilmDag.py took 0.472 seconds
[2024-01-29T20:13:13.226+0100] {processor.py:161} INFO - Started process (PID=9182) to work on /home/ubuntu/airflow/dags/FilmDag.py
[2024-01-29T20:13:13.274+0100] {processor.py:830} INFO - Processing file /home/ubuntu/airflow/dags/FilmDag.py for tasks to queue
[2024-01-29T20:13:13.276+0100] {logging_mixin.py:188} INFO - [2024-01-29T20:13:13.275+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/FilmDag.py
[2024-01-29T20:13:13.358+0100] {logging_mixin.py:188} INFO - [2024-01-29T20:13:13.318+0100] {dagbag.py:348} ERROR - Failed to import: /home/ubuntu/airflow/dags/FilmDag.py
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/FilmDag.py", line 6, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-01-29T20:13:13.358+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/FilmDag.py
[2024-01-29T20:13:13.517+0100] {processor.py:183} INFO - Processing /home/ubuntu/airflow/dags/FilmDag.py took 0.319 seconds
[2024-01-29T20:14:05.364+0100] {processor.py:161} INFO - Started process (PID=9234) to work on /home/ubuntu/airflow/dags/FilmDag.py
[2024-01-29T20:14:05.366+0100] {processor.py:830} INFO - Processing file /home/ubuntu/airflow/dags/FilmDag.py for tasks to queue
[2024-01-29T20:14:05.367+0100] {logging_mixin.py:188} INFO - [2024-01-29T20:14:05.367+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/FilmDag.py
[2024-01-29T20:14:05.371+0100] {logging_mixin.py:188} INFO - [2024-01-29T20:14:05.370+0100] {dagbag.py:348} ERROR - Failed to import: /home/ubuntu/airflow/dags/FilmDag.py
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/FilmDag.py", line 6, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-01-29T20:14:05.371+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/FilmDag.py
[2024-01-29T20:14:05.401+0100] {processor.py:183} INFO - Processing /home/ubuntu/airflow/dags/FilmDag.py took 0.041 seconds
[2024-01-29T20:14:38.029+0100] {processor.py:161} INFO - Started process (PID=9269) to work on /home/ubuntu/airflow/dags/FilmDag.py
[2024-01-29T20:14:38.031+0100] {processor.py:830} INFO - Processing file /home/ubuntu/airflow/dags/FilmDag.py for tasks to queue
[2024-01-29T20:14:38.032+0100] {logging_mixin.py:188} INFO - [2024-01-29T20:14:38.031+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/FilmDag.py
[2024-01-29T20:14:38.036+0100] {logging_mixin.py:188} INFO - [2024-01-29T20:14:38.035+0100] {dagbag.py:348} ERROR - Failed to import: /home/ubuntu/airflow/dags/FilmDag.py
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/FilmDag.py", line 6, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-01-29T20:14:38.036+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/FilmDag.py
[2024-01-29T20:14:38.095+0100] {processor.py:183} INFO - Processing /home/ubuntu/airflow/dags/FilmDag.py took 0.071 seconds
[2024-01-29T20:15:23.155+0100] {processor.py:161} INFO - Started process (PID=9316) to work on /home/ubuntu/airflow/dags/FilmDag.py
[2024-01-29T20:15:23.159+0100] {processor.py:830} INFO - Processing file /home/ubuntu/airflow/dags/FilmDag.py for tasks to queue
[2024-01-29T20:15:23.161+0100] {logging_mixin.py:188} INFO - [2024-01-29T20:15:23.160+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/FilmDag.py
[2024-01-29T20:15:23.165+0100] {logging_mixin.py:188} INFO - [2024-01-29T20:15:23.164+0100] {dagbag.py:348} ERROR - Failed to import: /home/ubuntu/airflow/dags/FilmDag.py
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/FilmDag.py", line 6, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-01-29T20:15:23.165+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/FilmDag.py
[2024-01-29T20:15:23.194+0100] {processor.py:183} INFO - Processing /home/ubuntu/airflow/dags/FilmDag.py took 0.042 seconds
[2024-01-29T20:16:08.234+0100] {processor.py:161} INFO - Started process (PID=9368) to work on /home/ubuntu/airflow/dags/FilmDag.py
[2024-01-29T20:16:08.236+0100] {processor.py:830} INFO - Processing file /home/ubuntu/airflow/dags/FilmDag.py for tasks to queue
[2024-01-29T20:16:08.237+0100] {logging_mixin.py:188} INFO - [2024-01-29T20:16:08.237+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/FilmDag.py
[2024-01-29T20:16:08.241+0100] {logging_mixin.py:188} INFO - [2024-01-29T20:16:08.240+0100] {dagbag.py:348} ERROR - Failed to import: /home/ubuntu/airflow/dags/FilmDag.py
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/FilmDag.py", line 6, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-01-29T20:16:08.242+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/FilmDag.py
[2024-01-29T20:16:08.281+0100] {processor.py:183} INFO - Processing /home/ubuntu/airflow/dags/FilmDag.py took 0.050 seconds
[2024-01-29T20:16:56.056+0100] {processor.py:161} INFO - Started process (PID=9420) to work on /home/ubuntu/airflow/dags/FilmDag.py
[2024-01-29T20:16:56.075+0100] {processor.py:830} INFO - Processing file /home/ubuntu/airflow/dags/FilmDag.py for tasks to queue
[2024-01-29T20:16:56.076+0100] {logging_mixin.py:188} INFO - [2024-01-29T20:16:56.076+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/FilmDag.py
[2024-01-29T20:16:56.082+0100] {logging_mixin.py:188} INFO - [2024-01-29T20:16:56.082+0100] {dagbag.py:348} ERROR - Failed to import: /home/ubuntu/airflow/dags/FilmDag.py
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/FilmDag.py", line 6, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-01-29T20:16:56.083+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/FilmDag.py
[2024-01-29T20:16:56.130+0100] {processor.py:183} INFO - Processing /home/ubuntu/airflow/dags/FilmDag.py took 0.077 seconds
[2024-01-29T20:17:45.740+0100] {processor.py:161} INFO - Started process (PID=9477) to work on /home/ubuntu/airflow/dags/FilmDag.py
[2024-01-29T20:17:45.742+0100] {processor.py:830} INFO - Processing file /home/ubuntu/airflow/dags/FilmDag.py for tasks to queue
[2024-01-29T20:17:45.743+0100] {logging_mixin.py:188} INFO - [2024-01-29T20:17:45.743+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/FilmDag.py
[2024-01-29T20:17:45.747+0100] {logging_mixin.py:188} INFO - [2024-01-29T20:17:45.746+0100] {dagbag.py:348} ERROR - Failed to import: /home/ubuntu/airflow/dags/FilmDag.py
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/FilmDag.py", line 6, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-01-29T20:17:45.748+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/FilmDag.py
[2024-01-29T20:17:45.777+0100] {processor.py:183} INFO - Processing /home/ubuntu/airflow/dags/FilmDag.py took 0.041 seconds
[2024-01-29T20:18:29.845+0100] {processor.py:161} INFO - Started process (PID=9525) to work on /home/ubuntu/airflow/dags/FilmDag.py
[2024-01-29T20:18:29.847+0100] {processor.py:830} INFO - Processing file /home/ubuntu/airflow/dags/FilmDag.py for tasks to queue
[2024-01-29T20:18:29.848+0100] {logging_mixin.py:188} INFO - [2024-01-29T20:18:29.848+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/FilmDag.py
[2024-01-29T20:18:29.853+0100] {logging_mixin.py:188} INFO - [2024-01-29T20:18:29.851+0100] {dagbag.py:348} ERROR - Failed to import: /home/ubuntu/airflow/dags/FilmDag.py
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/FilmDag.py", line 6, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-01-29T20:18:29.853+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/FilmDag.py
[2024-01-29T20:18:29.883+0100] {processor.py:183} INFO - Processing /home/ubuntu/airflow/dags/FilmDag.py took 0.041 seconds
[2024-01-29T20:19:13.242+0100] {processor.py:161} INFO - Started process (PID=9592) to work on /home/ubuntu/airflow/dags/FilmDag.py
[2024-01-29T20:19:13.257+0100] {processor.py:830} INFO - Processing file /home/ubuntu/airflow/dags/FilmDag.py for tasks to queue
[2024-01-29T20:19:13.259+0100] {logging_mixin.py:188} INFO - [2024-01-29T20:19:13.258+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/FilmDag.py
[2024-01-29T20:19:13.263+0100] {logging_mixin.py:188} INFO - [2024-01-29T20:19:13.262+0100] {dagbag.py:348} ERROR - Failed to import: /home/ubuntu/airflow/dags/FilmDag.py
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/FilmDag.py", line 6, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-01-29T20:19:13.264+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/FilmDag.py
[2024-01-29T20:19:13.297+0100] {processor.py:183} INFO - Processing /home/ubuntu/airflow/dags/FilmDag.py took 0.059 seconds
[2024-01-29T20:19:57.767+0100] {processor.py:161} INFO - Started process (PID=9646) to work on /home/ubuntu/airflow/dags/FilmDag.py
[2024-01-29T20:19:57.769+0100] {processor.py:830} INFO - Processing file /home/ubuntu/airflow/dags/FilmDag.py for tasks to queue
[2024-01-29T20:19:57.770+0100] {logging_mixin.py:188} INFO - [2024-01-29T20:19:57.770+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/FilmDag.py
[2024-01-29T20:19:57.774+0100] {logging_mixin.py:188} INFO - [2024-01-29T20:19:57.773+0100] {dagbag.py:348} ERROR - Failed to import: /home/ubuntu/airflow/dags/FilmDag.py
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/FilmDag.py", line 6, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-01-29T20:19:57.774+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/FilmDag.py
[2024-01-29T20:19:57.815+0100] {processor.py:183} INFO - Processing /home/ubuntu/airflow/dags/FilmDag.py took 0.051 seconds
[2024-01-29T20:20:38.176+0100] {processor.py:161} INFO - Started process (PID=9693) to work on /home/ubuntu/airflow/dags/FilmDag.py
[2024-01-29T20:20:38.177+0100] {processor.py:830} INFO - Processing file /home/ubuntu/airflow/dags/FilmDag.py for tasks to queue
[2024-01-29T20:20:38.178+0100] {logging_mixin.py:188} INFO - [2024-01-29T20:20:38.178+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/FilmDag.py
[2024-01-29T20:20:38.182+0100] {logging_mixin.py:188} INFO - [2024-01-29T20:20:38.182+0100] {dagbag.py:348} ERROR - Failed to import: /home/ubuntu/airflow/dags/FilmDag.py
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/FilmDag.py", line 6, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-01-29T20:20:38.183+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/FilmDag.py
[2024-01-29T20:20:38.215+0100] {processor.py:183} INFO - Processing /home/ubuntu/airflow/dags/FilmDag.py took 0.044 seconds
